production:
  cloud_name: 'dcl9b1toi'
  api_key: '866944124588188'
  api_secret: 'D5AFhU54_y4Cus3yYoV7z7ssoRA'

development:
  cloud_name: 'dcl9b1toi'
  api_key: '866944124588188'
  api_secret: 'D5AFhU54_y4Cus3yYoV7z7ssoRA'
